#!/usr/bin/env node
/**
 * Generate every downstream copy of the house rules from the one source.
 *
 * The rules live as code in scanner/house-rules.js, because the web page has
 * no network and cannot fetch a JSON file at runtime. Everything else is
 * generated from there, so the page, the CLI and the skill can never drift:
 *
 *   house-rules.json                                  portable, importable
 *   .claude/skills/avoid-ai-writing/HOUSE-RULES.md    what the agent reads
 *   .claude/skills/avoid-ai-writing/SKILL.md          a delimited pointer
 *
 * `npm run rules:sync` writes them; `--check` verifies they are current and
 * exits 1 if not, which is what the test suite runs.
 *
 * The SKILL.md edit is the only change made to the vendored upstream skill.
 * It is fenced in HTML comments so it can be regenerated or stripped without
 * touching upstream's text, and the detector itself is untouched.
 */

const fs = require('fs');
const path = require('path');
const HouseRules = require('./house-rules.js');

const ROOT = path.join(__dirname, '..');
const SKILL_DIR = path.join(ROOT, '.claude', 'skills', 'avoid-ai-writing');
const JSON_PATH = path.join(ROOT, 'house-rules.json');
const DOC_PATH = path.join(SKILL_DIR, 'HOUSE-RULES.md');
const SKILL_PATH = path.join(SKILL_DIR, 'SKILL.md');

const BEGIN = '<!-- PROOF-DESK:HOUSE-RULES:BEGIN -->';
const END = '<!-- PROOF-DESK:HOUSE-RULES:END -->';

function rulesJson() {
  return HouseRules.toJSON(HouseRules.DEFAULT_RULES) + '\n';
}

function escapeCell(s) {
  return String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function rulesDoc() {
  const rules = HouseRules.normalize(HouseRules.DEFAULT_RULES);
  const rows = rules
    .map((r) => {
      const replacement = r.replacement || '—';
      return `| \`${escapeCell(r.label)}\` | ${escapeCell(replacement)} | ${escapeCell(r.note || '')} |`;
    })
    .join('\n');

  return `# House rules

<!-- Generated by scanner/sync-rules.js from scanner/house-rules.js.
     Edit the rules there (or export from the Proof Desk page and re-sync);
     do not hand-edit this file. -->

These are the writer's own standing rules, on top of the AI-writing patterns
in [SKILL.md](./SKILL.md). Apply them whenever you draft or edit prose for
this person, not only when they ask for an AI-writing audit.

| Pattern | Replacement | Why |
|---|---|---|
${rows}

## How to apply them

- Report violations under a **HOUSE RULES** heading, separate from the
  AI-writing findings. They are a different kind of problem: a house rule is
  a stated preference, not evidence about how the text was produced.
- A replacement of \`(rewrite)\` or \`(remove)\` is an instruction, not a
  substitution. Rewrite the sentence or cut the claim; do not paste the
  literal word "(rewrite)" into the draft.
- A replacement listing options (\`strong, solid\`) means pick whichever fits.
- \`leverage\` is banned as a verb only. The noun ("financial leverage", "the
  leverage he had") is fine and must not be flagged.
- \`two years coding\` is a recurring factual error, not a style note. The
  correct figure is three years.

## Keeping this in sync

The rules are code in \`scanner/house-rules.js\` and are exported to
\`house-rules.json\` at the repo root. The Proof Desk page can export and
import that same JSON, so a rule added in the browser can be moved here by
replacing \`DEFAULT_RULES\` and running \`npm run rules:sync\`.
`;
}

function skillAddendum() {
  return [
    BEGIN,
    '',
    '## House rules (local addition)',
    '',
    "This copy of the skill is bundled with Proof Desk, which adds the writer's",
    'own standing bans on top of the patterns above — banned words, preferred',
    'replacements, and recurring factual errors.',
    '',
    '**Read [HOUSE-RULES.md](./HOUSE-RULES.md) and apply it alongside this file.**',
    'Report house-rule violations under their own HOUSE RULES heading, separate',
    'from the AI-writing findings: a house rule is a stated preference, not',
    'evidence about how the text was produced.',
    '',
    'This block is generated by `scanner/sync-rules.js`. Everything outside the',
    'two markers is upstream text, unmodified.',
    '',
    END,
  ].join('\n');
}

function skillWithAddendum(current) {
  const addendum = skillAddendum();
  const from = current.indexOf(BEGIN);
  if (from >= 0) {
    const to = current.indexOf(END);
    if (to < 0) throw new Error('SKILL.md has an opening marker with no closing marker.');
    return current.slice(0, from) + addendum + current.slice(to + END.length);
  }
  return current.replace(/\s*$/, '\n') + '\n' + addendum + '\n';
}

function targets() {
  return [
    { path: JSON_PATH, want: rulesJson() },
    { path: DOC_PATH, want: rulesDoc() },
    {
      path: SKILL_PATH,
      want: skillWithAddendum(fs.readFileSync(SKILL_PATH, 'utf8')),
    },
  ];
}

function sync({ check = false } = {}) {
  const stale = [];
  for (const t of targets()) {
    const current = fs.existsSync(t.path) ? fs.readFileSync(t.path, 'utf8') : null;
    if (current === t.want) continue;
    stale.push(path.relative(ROOT, t.path));
    if (!check) fs.writeFileSync(t.path, t.want);
  }
  return stale;
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  const stale = sync({ check });
  if (!stale.length) {
    process.stdout.write('house rules: all generated files are current\n');
    process.exit(0);
  }
  if (check) {
    process.stderr.write(
      `house rules out of sync:\n${stale.map((s) => `  ${s}`).join('\n')}\n` +
        'Run: npm run rules:sync\n'
    );
    process.exit(1);
  }
  process.stdout.write(`house rules: wrote\n${stale.map((s) => `  ${s}`).join('\n')}\n`);
}

module.exports = { sync, rulesJson, rulesDoc, skillWithAddendum, BEGIN, END, JSON_PATH, DOC_PATH, SKILL_PATH };
