#!/usr/bin/env node
/**
 * Generate every downstream copy of the house rules from the one source.
 *
 * The rules live as code in scanner/house-rules.js, because the web page has
 * no network and cannot fetch a JSON file at runtime. Everything else is
 * generated from there, so the page, the CLI and the skill can never drift:
 *
 *   house-rules.json                                  portable, importable
 *   .claude/skills/avoid-ai-writing/HOUSE-RULES.md    what the agent reads
 *   .claude/skills/avoid-ai-writing/SKILL.md          a delimited pointer
 *
 * `npm run rules:sync` writes them; `--check` verifies they are current and
 * exits 1 if not, which is what the test suite runs.
 *
 * The SKILL.md edit is the only change made to the vendored upstream skill.
 * It is fenced in HTML comments so it can be regenerated or stripped without
 * touching upstream's text, and the detector itself is untouched.
 */

const fs = require('fs');
const path = require('path');
const HouseRules = require('./house-rules.js');
const Corpus = require('./corpus.js');
const Fingerprint = require('./fingerprint.js');

const ROOT = path.join(__dirname, '..');
const SKILL_DIR = path.join(ROOT, '.claude', 'skills', 'avoid-ai-writing');
const JSON_PATH = path.join(ROOT, 'house-rules.json');
const DOC_PATH = path.join(SKILL_DIR, 'HOUSE-RULES.md');
const VOICE_PATH = path.join(SKILL_DIR, 'VOICE.md');
const SKILL_PATH = path.join(SKILL_DIR, 'SKILL.md');

const BEGIN = '<!-- PROOF-DESK:HOUSE-RULES:BEGIN -->';
const END = '<!-- PROOF-DESK:HOUSE-RULES:END -->';

function rulesJson() {
  return HouseRules.toJSON(HouseRules.DEFAULT_RULES) + '\n';
}

function escapeCell(s) {
  return String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function rulesDoc() {
  const rules = HouseRules.normalize(HouseRules.DEFAULT_RULES);
  const rows = rules
    .map((r) => {
      const replacement = r.replacement || '—';
      return `| \`${escapeCell(r.label)}\` | ${escapeCell(replacement)} | ${escapeCell(r.note || '')} |`;
    })
    .join('\n');

  return `# House rules

<!-- Generated by scanner/sync-rules.js from scanner/house-rules.js.
     Edit the rules there (or export from the Proof Desk page and re-sync);
     do not hand-edit this file. -->

These are the writer's own standing rules, on top of the AI-writing patterns
in [SKILL.md](./SKILL.md). Apply them whenever you draft or edit prose for
this person, not only when they ask for an AI-writing audit.

| Pattern | Replacement | Why |
|---|---|---|
${rows}

## How to apply them

- Report violations under a **HOUSE RULES** heading, separate from the
  AI-writing findings. They are a different kind of problem: a house rule is
  a stated preference, not evidence about how the text was produced.
- A replacement of \`(rewrite)\` or \`(remove)\` is an instruction, not a
  substitution. Rewrite the sentence or cut the claim; do not paste the
  literal word "(rewrite)" into the draft.
- A replacement listing options (\`strong, solid\`) means pick whichever fits.
- \`leverage\` is banned as a verb only. The noun ("financial leverage", "the
  leverage he had") is fine and must not be flagged.
- \`two years coding\` is a recurring factual error, not a style note. The
  correct figure is three years.

## Keeping this in sync

The rules are code in \`scanner/house-rules.js\` and are exported to
\`house-rules.json\` at the repo root. The Proof Desk page can export and
import that same JSON, so a rule added in the browser can be moved here by
replacing \`DEFAULT_RULES\` and running \`npm run rules:sync\`.
`;
}

function voiceDoc() {
  return `# Voice: the reference corpus

<!-- Generated by scanner/sync-rules.js. Do not hand-edit. -->

Proof Desk can compare a draft against a **reference corpus** of the writer's
own writing. If a corpus file is available, read it before editing prose for
this person: it is the best available evidence of how they actually write.

## The constraint that matters most

**Every sample must be the writer's own unassisted writing.**

If a sample was drafted with an assistant, the fingerprint built from it
describes the assistant, not the writer — and every comparison afterwards is
confidently wrong in the most damaging direction: it will tell the writer
their own voice is off, while rating assistant-shaped prose as authentic.

Much recent professional writing is assistant-drafted. Assume nothing. If you
are asked to add a sample and cannot confirm the writer wrote it unaided, say
so rather than adding it.

Proof Desk screens every sample with the AI detector on the way in and
excludes anything scoring above the "${Corpus.MAX_CLEAN_BAND}" band. That
catches the obvious case; it does not make an unverified sample safe.

## Where the corpus lives

The CLI resolves it from the first of:

    --corpus <file>
    $PROOF_DESK_CORPUS
    ./.proof-desk-corpus.json
    ~/.proof-desk/corpus.json

The web page keeps its own copy in browser storage and exports the same JSON.

## What makes a corpus usable

| | |
|---|---|
| Samples | ${Corpus.MIN_SAMPLES} minimum, ${Corpus.TARGET_SAMPLES} recommended |
| Words per sample | ${Corpus.MIN_SAMPLE_WORDS} minimum |
| Total words | ${Corpus.MIN_TOTAL_WORDS} minimum, ${Corpus.STRONG_TOTAL_WORDS}+ for full confidence |

Below those floors the tool reports low confidence rather than producing a
number that looks authoritative. Respect that: a thin corpus is a weak claim
about someone's voice, and should be described as one.

## Written and spoken samples

A sample is \`written\` or \`spoken\`. Transcripts of talks, courses and
interviews are \`spoken\`: their sentence lengths, paragraph breaks,
punctuation and contractions belong to whoever transcribed them — auto-captions
carry no punctuation at all — so those metrics ignore transcripts entirely.
Vocabulary and phrasing survive transcription, so spoken samples do count
toward those.

## The profile

Each metric carries its own data requirement and is marked unavailable, with
a reason, until the corpus meets it. Mean sentence length settles after a few
hundred words; claiming someone *never* writes a word needs thousands. There
is deliberately no single confidence number.

| Metric | Needs | Basis |
|---|---|---|
${Fingerprint.METRICS.map(
  (m) => `| ${m.label} | ${m.needWords} words | ${m.writtenOnly ? 'written only' : 'written + spoken'} |`
).join('\n')}

Numeric metrics are stored as the **band** the corpus actually shows across
samples, not as an average. A writer who mentors students, files support
reports and negotiates with vendors has a real sentence length that is a
range. Flag a draft only when it falls outside that range; comparing against
a mean the writer never actually writes at flags their own work constantly.

Every metric carries excerpts from the corpus that produced it. If you report
a number, you can quote the sentences behind it.
`;
}

function skillAddendum() {
  return [
    BEGIN,
    '',
    '## House rules (local addition)',
    '',
    "This copy of the skill is bundled with Proof Desk, which adds the writer's",
    'own standing bans on top of the patterns above — banned words, preferred',
    'replacements, and recurring factual errors.',
    '',
    '**Read [HOUSE-RULES.md](./HOUSE-RULES.md) and apply it alongside this file.**',
    'Report house-rule violations under their own HOUSE RULES heading, separate',
    'from the AI-writing findings: a house rule is a stated preference, not',
    'evidence about how the text was produced.',
    '',
    'It can also carry a reference corpus of the writer\'s own writing. See',
    '[VOICE.md](./VOICE.md) — and note the constraint there: every sample must be',
    'unassisted, or the resulting voice profile describes the assistant.',
    '',
    'This block is generated by `scanner/sync-rules.js`. Everything outside the',
    'two markers is upstream text, unmodified.',
    '',
    END,
  ].join('\n');
}

function skillWithAddendum(current) {
  const addendum = skillAddendum();
  const from = current.indexOf(BEGIN);
  if (from >= 0) {
    const to = current.indexOf(END);
    if (to < 0) throw new Error('SKILL.md has an opening marker with no closing marker.');
    return current.slice(0, from) + addendum + current.slice(to + END.length);
  }
  return current.replace(/\s*$/, '\n') + '\n' + addendum + '\n';
}

function targets() {
  return [
    { path: JSON_PATH, want: rulesJson() },
    { path: DOC_PATH, want: rulesDoc() },
    { path: VOICE_PATH, want: voiceDoc() },
    {
      path: SKILL_PATH,
      want: skillWithAddendum(fs.readFileSync(SKILL_PATH, 'utf8')),
    },
  ];
}

function sync({ check = false } = {}) {
  const stale = [];
  for (const t of targets()) {
    const current = fs.existsSync(t.path) ? fs.readFileSync(t.path, 'utf8') : null;
    if (current === t.want) continue;
    stale.push(path.relative(ROOT, t.path));
    if (!check) fs.writeFileSync(t.path, t.want);
  }
  return stale;
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  const stale = sync({ check });
  if (!stale.length) {
    process.stdout.write('house rules: all generated files are current\n');
    process.exit(0);
  }
  if (check) {
    process.stderr.write(
      `house rules out of sync:\n${stale.map((s) => `  ${s}`).join('\n')}\n` +
        'Run: npm run rules:sync\n'
    );
    process.exit(1);
  }
  process.stdout.write(`house rules: wrote\n${stale.map((s) => `  ${s}`).join('\n')}\n`);
}

module.exports = { sync, rulesJson, rulesDoc, voiceDoc, skillWithAddendum, BEGIN, END, JSON_PATH, DOC_PATH, VOICE_PATH, SKILL_PATH };
